
name: Aplicación de Python con MongoDB

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pymongo sqlite3

    - name: Run the script
      run: |
        python nombre_de_tu_script.py